export const OPEN ='OPEN'
export const PROGRESS='PROGRESS'
export const CLOSED= 'CLOSED'
export const BLOCKED= 'BLOCKED'
export const TECHNICIAN='TECHNICIAN'
export const USER='USER'
export const HOUSEKEEPING='HOUSEKEEPING'
export const MANAGER='MANAGER'
export const ADMIN='ADMIN'
export const widthGetFullScreen=768
export const sideBarWidthCons="200px"
export const minSideWidth="100px"
export const maxSideWidth="200px"