export const OPEN ='OPEN'
export const PROGRESS='PROGRESS'
export const CLOSED= 'CLOSED'
export const BLOCKED= 'BLOCKED'
export const COMPLETED='COMPLETED'
export const TECHNICIAN='TECHNICIAN'
export const USER='USER'
export const HOUSEKEEPING='HOUSEKEEPING'
export const MANAGER='MANAGER'
export const ADMIN='ADMIN'
export const widthGetFullScreen=768
export const sideBarWidthCons="200px"
export const minSideWidth="100"
export const maxSideWidth="200"
export const NotAssigned="Not Assigned"
export const NotAssignedId="NotAssigned"
export const InStock="In Stock"
export const OutOfStock="Out of Stock"
export const LowStock='Low Stock'